name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies with yarn v3
        run: |
          corepack prepare yarn@3.2.3 --activate
          yarn install

      - name: Build
        run: yarn build
#  test:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Enable corepack
#        run: corepack enable
#
#      - name: Install dependencies
#        run: yarn install
#
#      - name: Prepare yarn
#        run: corepack prepare yarn@3.2.3 --activate
#
#      - name: Test
#        run: yarn test